apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-deployment
  labels:
    name: welcome-deployment
spec:
    replicas:4  
  selector:
    matchLabels:
      name: welcome
  template:
    metadata:
      labels:
        name: welcome
    spec:
      subdomain: primary
      containers:
      - name: welcome
        image: sravaniavusherla/welcome:latest
        
